// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMZsD5jDWB-QWK6EHCHZGRRmWUfQ2smzs',
    appId: '1:357982763843:web:74691d76e8688213e20df6',
    messagingSenderId: '357982763843',
    projectId: 'travel-app-b176e',
    authDomain: 'travel-app-b176e.firebaseapp.com',
    storageBucket: 'travel-app-b176e.firebasestorage.app',
    measurementId: 'G-CX91CJ1SBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxMFPxSnEWhD0WBQvscHx3Qa-is8q-RcI',
    appId: '1:357982763843:android:7403fb73b15254efe20df6',
    messagingSenderId: '357982763843',
    projectId: 'travel-app-b176e',
    storageBucket: 'travel-app-b176e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB06AW1T7JHV9fDqIq8Ap6SiACx67YiWPo',
    appId: '1:357982763843:ios:8038c901ca76e25ce20df6',
    messagingSenderId: '357982763843',
    projectId: 'travel-app-b176e',
    storageBucket: 'travel-app-b176e.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB06AW1T7JHV9fDqIq8Ap6SiACx67YiWPo',
    appId: '1:357982763843:ios:8038c901ca76e25ce20df6',
    messagingSenderId: '357982763843',
    projectId: 'travel-app-b176e',
    storageBucket: 'travel-app-b176e.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMZsD5jDWB-QWK6EHCHZGRRmWUfQ2smzs',
    appId: '1:357982763843:web:78f4a57ba9b95a8ee20df6',
    messagingSenderId: '357982763843',
    projectId: 'travel-app-b176e',
    authDomain: 'travel-app-b176e.firebaseapp.com',
    storageBucket: 'travel-app-b176e.firebasestorage.app',
    measurementId: 'G-LXE4WRLWL6',
  );
}
